language: python
python:
  - "3.6.0"
services:
  - mysql
env:
  global:
    - DJANGO_SETTINGS_MODULE="config.settings.travisCI"
    - PYTHONPATH="/home/travis/build/malrefai/board-project"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
  matrix:
  - DJANGO=2.1 DB=mysql
# command to install dependencies
install:
  - pip install -r requirements/travisCI.txt
before_script:
  - mysql -e 'create database travis_ci_db;'
  - python manage.py syncdb --noinput
script:
  - yapf -vv -pri board/
  - flake8 `ls -d */ | egrep -v 'config|requirements'`
  - python manage.py migrate
  - coverage run ./manage.py test
# publish coverage only after a successful build
after_success:
  - codecov
notifications:
  email: false
branches:
  only:
    - master
    - develop
